#=================================================
# https://github.com/yangchuansheng/kubesphere-insights
# Lisence: MIT
# Author: Carson Yang
# Blog: https://icloudnative.io
#=================================================

name: KubeSphere Insights

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  #watch:
    #types: started

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +%Y%m%d-%H%M%S)"
      
    - name: Start SSH via Ngrok
      if: ${{ failure() }}
      run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
      env:
       # After sign up on the https://ngrok.com/
       # You can find this token here: https://dashboard.ngrok.com/get-started/setup
       NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

       # This password you will use when authorizing via SSH 
       USER_PASS: ${{ secrets.USER_PASS }}
       GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Don't kill instace
      if: ${{ failure() }}
      run: sleep 12h # Prevent to killing instance after failure

    - name: Contributors
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: cat ks_all_contributors.sh
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ks_all_contributors_${{ steps.date.outputs.date }}.txt
        path: ./
